### ISSUE TITLE
Initial port from Javascript library

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-validate-py#1]
# Description

[We have a working implementation of this in Javascript](https://github.com/okfn/datapackage-validate).

We need a Python version. It depends on the new `data package-registry-py` lib.
# Tasks
- [x] Port existing Javascript functionality to Python
  - [x] Note the config options
- [x] Port existing test cases to Python
- [x] Write up basic documentation on how it works (eg: 1 paragraph, and an example)
- [x] Runs on Python 2.7.x and 3.3.x and above
  - [x] Use compat pattern that we use [here](https://github.com/okfn/goodtables/blob/master/goodtables/compat.py) [here](https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/compat.py) [here](https://github.com/okfn/spd-admin/blob/master/spd_admin/compat.py). This is based on some popular libs like [requests](https://github.com/kennethreitz/requests/blob/master/requests/compat.py), as well as the [Python porting guide](https://docs.python.org/3/howto/pyporting.html)
- [x] Publish to PyPI as `datapackage-validate`
